Update panel visibility checks to use TextBlock proxy
Replaced direct checks of the WPF Border panel with checks for the existence of a child TextBlock ("lblDetailsTitle") as a proxy for panel visibility in UI tests. This improves reliability since Border controls lack automation peers.

Achieved with the following co-pilot instructions:
- During the building_details tests, the left-click on the building works correctly and the building's details are loaded into the details panel, but the test fails in the "Then the building details panel should be visible" step with the following error: "    Then the building details panel should be visible           # features/steps/building_details_steps.py:155
      Traceback (most recent call last):
        File "C:\Python310\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
          ctrl = wait_until_passes(
        File "C:\Python310\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
          raise err
      pywinauto.timings.TimeoutError

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Python310\lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Python310\lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\building_details_steps.py", line 158, in step_details_visible
          wait_until(
        File "C:\Python310\lib\site-packages\pywinauto\timings.py", line 359, in wait_until
          func_val = func(*args, **kwargs)
        File "features\steps\building_details_steps.py", line 160, in <lambda>
          func=lambda: panel.is_visible(),
        File "C:\Python310\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
          ctrls = self.__resolve_control(self.criteria)
        File "C:\Python310\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
          raise e.original_exception
        File "C:\Python310\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
          func_val = func(*args, **kwargs)
        File "C:\Python310\lib\site-packages\pywinauto\application.py", line 222, in __get_ctrl
          ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
        File "C:\Python310\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
          raise ElementNotFoundError(kwargs)
      pywinauto.findwindows.ElementNotFoundError: {'auto_id': 'pnlDetails', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - 'City GIS 3D Viewer', Window, 5375796>, 'backend': 'uia'}".